Mseg3D应该就是用的open-mmlab环境跑的
# NOTE: add lidarseg3d to PYTHONPATH by adding the following line to ~/.bashrc (change the path accordingly) and reactivating it
export PYTHONPATH="${PYTHONPATH}:PATH_TO_lidarseg3d"

export PATH=/home/rd016/env_cmake3.25.3/bin:$PATH   //（路径要对应上）
export PYTHONPATH="${PYTHONPATH}:/data/luochao/Paper/lidarseg3d/nuscenes-devkit/python-sdk"

# 网络错误 -i https://pypi.tuna.tsinghua.edu.cn/simple


# 构建数据集部分：

    # 应对找不到det3d，不要进到ops一个一个编译，没用
    export PYTHONPATH=/data/luochao/Paper/lidarseg3d:$PYTHONPATH # 1

    waymo数据集似乎有点问题，
    ImportError: cannot import name 'segmentation_metrics_pb2' from 'waymo_open_dataset.protos' 
    (/home/luochao/.conda/envs/open-mmlab/lib/python3.7/site-packages/waymo_open_dataset/protos/__init__.py)
    但是文件其实都已经生成好了，最后无奈注释
    /data/luochao/Paper/lidarseg3d/det3d/datasets/__init__.py的5-6行 # 这个没用，最后还是需要用proto解析所有python文件

    # 用于解决已经使用proto解析之后仍然找不到文件的错误
    export PYTHONPATH=%PYTHONPATH:/data/luochao/Paper/lidarseg3d/waymo-open-dataset/src # 2

    export PYTHONPATH=%PYTHONPATH:/data/luochao/Paper/lidarseg3d/apex # 3

    这条命令是1、2和3的融合版，三条命令执行有顺序要求，直接用这条省事
    export PYTHONPATH=/data/luochao/Paper/lidarseg3d:/data/luochao/Paper/lidarseg3d/waymo-open-dataset/src:/data/luochao/Paper/lidarseg3d/apex:$PYTHONPATH

    报错：
        ImportError: cannot import name 'builder' from 'google.protobuf.internal' (/home/luochao/.conda/envs/open-mmlab/lib/python3.7/site-packages/google/protobuf/internal/__init__.py)
    解决：
        pip install protobuf==3.20.3

    报错： 
        assert table_name in self.table_names, "Table {} not found".format(table_name)
    解决：
        在输出的信息中有category、sensor、log等等的具体数量，但是没有lidarseg，说明nuscenes-devkit根本没有尝试去加载lidarseg
        预计是nuscenes-devkit版本太老导致（1.0.5）
        pip install nuscenes-devkit>=1.1.5
        最后安装了1.1.10版本，解决问题

# 实验部分
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 \
python -m torch.distributed.launch \
--nproc_per_node=8 \
--master_port=17045 \
tools/train.py configs/semanticnusc/MSeg3D/vfe_unetscn3d_hrnetw18_lr1en2_e12.py

CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node=6 ./tools/train.py \ 
configs/semanticnusc/MSeg3D/semnusc_avgvfe_unetscn3d_lidarbaseline_lr1en2_e12.py --tcp_port 17045

环境配置：
1、184有污染问题，建好环境后，加上export PYTHONNOUSERSITE=1 和 unset PYTHONPATH清除污染
2、pip install waymo-open-dataset-tf-2-6-0==1.4.3 -i https://pypi.tuna.tsinghua.edu.cn/simple
    能解决这个包的安装问题，直接一起装就算有指定最后那个路径也没有，逆天